mongodb:
  uri: "mongodb://mongo:27017"
  db_name: "trading"
  collection_name: "signals"

ccxt:
  exchange_id: "binance"
  api_key: ""
  secret: ""

trade_parameters:
  buy_enabled: True
  one_day_rsi_limit_buy: 65
  calculation_period: 15
  calculation_period_type: 0 # 0- minute ,1- hour ,2-day ,3-week 
  MINIMUM_TRADE_AMOUNT: 15
  MAXIMUM_TRADE_AMOUNT: 50
  RSI_BUY_LIMIT: 31
  rsi_sell_limit: 65
  rejected_list: ["BNB", "BSW","ETH","USDC","BUSD","FDUSD","TUSD","USDP"]  # Örnek reddedilen semboller listesi
  volume_limit: 1000000 # bu birimin altındaki hacimler kontrol dışı tutulacak
  sell_profit1 : 1.15
  sell_profit2 : 1.1
  sell_profit3 : 1.09
  sell_difference_rsi : 33
  sell_profit_1_rsi_level: 62
  

settings:
  use_multiprocessing: False  # Çoklu işlem kullanımı
