# docker-compose.yml
version: '3.8'

services:
  autobot:
    image: nvrbox/autobot:1.0.3
    container_name: AUTOBOT
    volumes:
    - ./logs:/bot/logs
    - ./config.yaml:/bot/config.yaml
    - ./botmain.py:/bot/main.py
    depends_on:
      - mongo
    restart: on-failure
  mongo:
    image: mongo:7.0.4
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    restart: on-failure

  autoschedule:
    image: nvrbox/autoschedule:1.0.3
    container_name: AUTOSCHEDULE
    depends_on:
      - mongo
    restart: on-failure
volumes:
  mongo-data:
