# docker-compose.yml
version: '3.8'

services:
  bot:
    build: .
    container_name: BOT
    volumes:
    - ./logs:/bot/logs
    #   - ./config.yaml:/bot.config.yaml
    depends_on:
      - mongo
    restart: on-failure

  mongo:
    image: mongo:7.0.4
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    restart: on-failure

  schedule:
    build:
      context: .
      dockerfile: SchDockerfile
    container_name: SCHEDULE
    depends_on:
      - mongo
    restart: on-failure
volumes:
  mongo-data:
